---
title: Review for Unit Four # Title of the document

execute:               # Default settings for code blocks
  warning: false       # Do not print warnings
  message: false       # Do not print messages
  size: "scriptsize"   # Set code size to script size

# Below will do html by default. To render the entire project
# Use the following code:
# quarto::quarto_render("Review.qmd")
format:
  html:       # Specify HTML formatting options 
    number-sections: true      # Number Sections
    code-fold: true            # Button to show code
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables and figures
  pdf:        # Specify .pdf formatting options 
    documentclass: article     # Document Class
    number-sections: true      # Number Sections
    reference-section-title: "References" # Title for reference section
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables 
    geometry:
      - top=0.75in
      - left=0.75in
      - bottom=0.75in
      - right=0.75in
format-links: [pdf]
---
```{r}
#| echo: false

default_chunk_hook  <- knitr::knit_hooks$get("chunk")

latex_font_size <- c("Huge", "huge", "LARGE", "Large", 
                     "large", "normalsize", "small", 
                     "footnotesize", "scriptsize", "tiny")

knitr::knit_hooks$set(chunk = function(x, options) {
  x <- default_chunk_hook(x, options)
  if(options$size %in% latex_font_size) {
    paste0("\n \\", options$size, "\n\n", 
      x, 
      "\n\n \\normalsize"
    )
  } else {
    x
  }
})
knitr::opts_knit$set(root.dir = here::here())
```

This unit will tell us how to use our data analysis and probability tools to come to conclusions about a general population based on a smaller, representative sample. We will do this by first choosing a distribution to fit the data, then finding values for the parameters of these distributions. We will choose the values that make the observed data the most likely.

# Point Estimation
A point estimator $\theta (X) = \theta (X_1, X_2, ... X_n)$ is any function of the sample $\bf{X}$. Therefore, any statistic is a point estimator. Correspondingly, $\theta (x) =\theta (x_1, x_2, ... x_n)$ is a point estimate. Fixed $\theta (x)$ is a realization of random $\theta (X)$.

Because a point estimator is a statistic, it is random and has its own distribution (a sampling distribution). We will explore two different methods for finding point estimators: Method of Moments, and Maximum Likelihood. 

Before going into the estimators, we discuss two rules: Law of Large Numbers, and Central Limit Theorem. 

The Law of Large numbers says that, for a sample with finite variance, as the size of the sample increases, the sample mean (mean of the sample) gets closer to the population mean (mean of the larger population). 

The Central Limit Theorem says that as the size of a sample increases, its distribution becomes more and more Gaussian until $ n \geq 30$, at which point it becomes approximately Gaussian. This is true regardless of the population's underlying distribution.  

# Method of Moments

Sample moments are the average of powers of the observed sample data. The following is done with the mean.

This is the mean of the observed sample data.
$x_{bar} = m_1 = \frac{1}{n}\sum_{i=1}^n x_i^1$,

This is the mean of the observed sample data squared. 
$x_{bar}^2 = m_2 = \frac{1}{n}\sum_{i=1}^n x_i^2$,

This is the mean of the observed sample data cubed. 
$x_{bar}^3 = m_3 = \frac{1}{n}\sum_{i=1}^n x_i^3$

Population moments are the expected values or population means of powers of the random variable of interest. For example,

This is the expected value of the mean: 
$\mu_1 = E(X^1)$

This is the expected value of the mean squared: 
$\mu_2 = E(X^2)$

This is the expected value of the mean cubed: 
$\mu_3 = E(X^3)$.

Next, we equate the first k sample moments to the first k population moments and solve for $\theta$. In this example, we will only use $k =1$ or $k=2$. For these, we will create and solve an approximate system of equations. 

$E(X^1) \approx m_1 = \frac{1}{n}\sum_{i=1}^n x_i^1$

$E(X^2) \approx m_2 = \frac{1}{n}\sum_{i=1}^n x_i^2$.

We then solve the equations by using nleqslv(), and choose the parameters that make the sample moments match the population moments. This works because of the law of large numbers.

# Maximum Likelihood estimations

The Maximum Likelihood Estimations come from the log-likelihood function. A $\theta$ value that maximizes the likelihood function is a maximum likelihood estimate, and is the value of $\theta$ that maximizes the probability of observing the data x. In practice, this is computed by using optim() to find the minimum of the negative log-likelihood function. 

# Comparing point estimators

Estimators have bias, precision, and mean squared error (MSE). 

Bias deals with accuracy, which means how accurate a point estimator is at estimating the population-level parameter $\theta$ on average. Bias is calculated as
$Bias_\theta(\hat\theta) = E(\hat\theta - \theta)$. However, in real scenarios, we do not know the true value of the population parameter and thus cannot calculate bias. 

Precision is related to the variance of a point estimator. It is calculated as $Precision_\theta(\hat\theta) = \frac{1}{var_\theta(\hat\theta)}$. Small variance means high precision.

Accuracy and precision have notable differences. Using darts as an example, if you are accurate and precise, you will hit the bullseye three times. If you are accurate but not precise, you will hit the same non-bullseye spot three times. If you are precise but not accurate, you will hit three spots that form an equilateral triangle around the bullseye. If you are not accurate and not precise, you will miss the bullseye in three random locations. 

The MSE combines information from the precision and bias. 

$MSE_\theta(\hat\theta) = var_\theta(\hat\theta) + Bias^2_\theta(\hat\theta)$

When comparing estimators, we want an estimator that is unbiased, and has the lowest variance. 

# Sampling distributions

The distribution of a statistic is called its sampling distribution. When talking about estimators, which are statistics, we say that a sampling distribution describes how the estimator $\hat\theta$ varies in repeated sampling from a population. 

Resampling is a technique that involves taking repeated, random samples from an original, representative sample to mimic reproducing an experiment on the population. For each random sample taken from the original, we can calculate summary statistics or estimates. To assess the sampling distribution of any statistic or estimator, we can plot a histogram of the statistics for all resamples and a density curve. The curve will estimate the sampling distribution. 

To perform resampling:
1. Treat the original sample as a population, and take a resample of the same size with replacement. 
2. Compute the statistic of interest on the resample, and store it. 

In the end, we have a sample of observations of the resample that we can summarize with a histogram and statistics like the mean, variance, skewness, and kurtosis. 

For the a random sample from a Gaussian distribution, the sample mean has a gaussian distribution. This means that the sample mean is an unbiased estimator of the population mean.

For a random sample NOT from a Gaussian distribution, as n increases, the distribution of the sample mean becomes approximately Gaussian. 

When talking about the sampling distribution of the sample mean, we say that the sampling distribution is approximately Gaussian if either of the following are true: The sample is representative, or $n\geq 30$. This works for many distributions, including skewed ones such as Exponential, Gamma, and Lognormal. 