project:
  type: website
  output-dir: .

website:
  title: "BLAH"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Lab 2/Lab2WriteUp.html
        text: Lab 2
      - href: Lab 3/Lab3WriteUp.html
        text: Lab 3
      - href: Lab 4/Lab4WriteUp.html
        text: Lab 4
      - href: Lab 5/Lab5WriteUp.html
        text: Lab 5
      - href: Lab 8/Lab8WriteUp.html
        text: Lab 8
      - href: Lab 10/Lab10WriteUp.html
        text: Lab 10
      - href: Lab 11/Lab11WriteUp.html
        text: Lab 11
      - href: Review/Review.html
        text: Unit 1 Review

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto