{
  "hash": "baf05991e46a72f5a7b4f1b97a2a30eb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\nMy probability statement: P(X >= 2). Since this is a discrete distribution, I choose to write it using the PMF, which represents it as f(2) + f(3), since the maximum value of x is 3. \n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(tidyverse)\n# library(ggplot2)\n#| install.packages(\"extraDistr\")\nlibrary(extraDistr) \nawinsprob=dbinom(x=2, prob = .7, size = 3)\nawinsprob1=dbinom(x = 3, prob=.7, size = 3)\n(awins=awinsprob1+awinsprob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = -1:4) |>\n  mutate(PMF = dbinom(x, prob=.7, size = 3))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot <- ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![Binomial distribution of probability of player A winning the match.](Lab8WriteUp_files/figure-pdf/fig-box-binom-1.pdf){#fig-box-binom fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution** \n\nMy probability statement is P(x=<1), which can be rewritten as f(0) + f(1) The two cases necessary to compute are the chances that 2 wins are reached with one loss, and two wins are reached with 0 losses. Summing these together gives the total probability that 2 wins are reached with 1 or 0 losses, which in the context of this best two-out-of-three match means that player A has won the game. The computed probability is the same as the  computed binomial distribution one, verifying that this is correct.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nawins1=dnbinom(prob = .7, size = 2, x=1)\nawins2=dnbinom(prob = .7, size = 2, x=0)\n(winprob=awins1+awins2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat <- tibble(x = -1:3) |>\n  mutate(PMF = dnbinom(x, prob=.7, size = 2))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMFs.plot <- ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x<2),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMFs.plot \n```\n\n::: {.cell-output-display}\n![Negative binomial distribution of probability of player A winning the match.](Lab8WriteUp_files/figure-pdf/fig-box-negbinom-1.pdf){#fig-box-negbinom fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"extraDistr\")\n# library(extraDistr)\n\n# awinsprobbeta=pbeta(q=2, shape1=7, shape2=3)\n# awinsprobbeta1=pbeta(q = 3, shape1=7, shape2=3)\n# (awins=awinsprobbeta1+awinsprobbeta)\n\nggdat <- tibble(x = seq(-1, 1, length.out=1000)) |>\n mutate(PDF = dbeta(x, shape1 = 7, shape2 = 3))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPDF_beta.plot <- ggplot(ggdat) +\n geom_line(aes(x = x, y = PDF/10)) +\n geom_ribbon(aes(x = x, ymin=0, ymax=PDF/10),\n fill=\"darkorchid2\", alpha=0.50)+\n geom_hline(yintercept = 0) +\n xlab(\"Win probability\") +\n ylab(\"Probability of having that win probability\") +\n theme_bw()\n\nPDF_beta.plot\n```\n\n::: {.cell-output-display}\n![Beta distribution of probability of player A winning the match.](Lab8WriteUp_files/figure-pdf/fig-box-betadist-1.pdf){#fig-box-betadist fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThis plot has a mean of .7 and is skewed right. This is because the inputs of alpha = 7 and beta = 3 say that player A has a greater chance of winning than player B. Comparing this to the binomial distribution, the binomial distribution models the outcome of a match given p, while this distribution allows for variance and uncertainty in p. \n\n\n1. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_integrand = function(p) {p*dbeta(p, shape1 = 7, shape2 = 3)}\n(mean = integrate(mean_integrand, lower = 0, upper = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.7 with absolute error < 7.8e-15\n```\n\n\n:::\n\n```{.r .cell-code}\nvar_integrand = function(p) {(p-.7)^2*dbeta(p, shape1 = 7, shape2 = 3)}\n(variance = integrate(var_integrand, lower = 0, upper = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.01909091 with absolute error < 2.1e-16\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe mean is .7, which reflects the probability of player A winning a match. The variance, which is .019, means that there is still a range of other possible values for p. This reflects the uncertainty brought in by the beta distribution.\n\n1. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\n**Solution**\nThe probability statement is P(x = 0.7). The probability of this occuring is 0, since win probability is continuous, and the probability of x being equal to an exact number is always 0 in a continuous distribution.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = seq(-1, 1, length.out=1000)) |>\n mutate(PDF = dbeta(x, shape1 = 7, shape2 = 3))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPDF_beta.plot <- ggplot(ggdat) +\n geom_line(aes(x = x, y = PDF)) +\n geom_linerange(data=tibble(x=.7) |> mutate(PDF=dbeta(x, shape1=7, shape2=3)), aes(x=x, ymin = 0, ymax=PDF), color=\"green\")+\n geom_hline(yintercept = 0) +\n xlab(\"Tensile Strength (MPa)\") +\n ylab(\"Density\") +\n theme_bw()\n\nPDF_beta.plot\n```\n\n::: {.cell-output-display}\n![The probability that player A has a .7 probability to win.](Lab8WriteUp_files/figure-pdf/fig-box-betabinom-.70-win-prob-1.pdf){#fig-box-betabinom-.70-win-prob fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nThe probability statement is P(x >= .5), which equals $1 - F(.5)$. This corresponds to a .91 chance that player A has a win probability of at least .5, as seen below.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(winprob_geq_50 = 1 - pbeta(q = .5, shape1 = 7, shape2 = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(ggdat) +\n geom_line(aes(x = x, y = PDF)) +\n geom_ribbon(data = ggdat |> filter(x < .5),\n  aes(x = x, ymin=0, ymax=PDF),\n  fill=\"darkorchid2\", alpha=0.50)+\n geom_hline(yintercept = 0) +\n xlab(\"Win probability\") +\n ylab(\"Density\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability that player A has at least a .5 probability to win.](Lab8WriteUp_files/figure-pdf/fig-box-betabinom-.5-win-prob-1.pdf){#fig-box-betabinom-.5-win-prob fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\n**Solution**\n\nMy probability statement is P(X <= x)=.9, or F^-1(x) = .9 Using the inverse CDF to calculate this value, my answer is .871.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = seq(0, 1, length.out=1000)) |>\n mutate(invCDF = qbeta(p=.90, shape1 = 7, shape2 = 3),\n          CDF = pbeta(x, shape1 = 7, shape2 = 3))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(ggdat) +\n geom_line(aes(x = x, y = CDF)) +\n geom_point(data = tibble(x=.8705027) |> mutate(CDF=pbeta(x,7,3)), aes(x=x, y=CDF), color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Win percentage\") +\n ylab(\"Cumulative probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability that player A has at least a .5 probability to win.](Lab8WriteUp_files/figure-pdf/fig-box-betabinom-90-percentile-win-prob-1.pdf){#fig-box-betabinom-90-percentile-win-prob fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\n**Solution**\n\nMy probability statement is P(X > 2). This can be written as f(2) +f (3), since this distribution is discrete. The calculated probability value is slightly less than the calculated binomial value, .764 compared to .784. This is likely because there is a higher probability in the beta binomial distribution of player A winning 0 or 3 games, which can be seen by those bars being higher than they were in the binomial distribution. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nawinsprob=dbbinom(x=2, alpha=7, beta = 3, size = 3)\nawinsprob1=dbbinom(x = 3, alpha=7, beta=3, size = 3)\n(awins=awinsprob1+awinsprob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = -1:4) |>\n  mutate(PMF = dbbinom(x, alpha=7, beta =3, size = 3))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot <- ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability that player A wins the match.](Lab8WriteUp_files/figure-pdf/fig-box-betabinom-player-A-wins-1.pdf){#fig-box-betabinom-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma_X &= \\sum_{i=0}^3 (i-\\mu_X) f_X(i)\n\\end{align*}\n\n**Solution**\n\nBinomial distribution: \n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nawinsprob=dbinom(x=2, prob = .7, size = 3)\nawinsprob1=dbinom(x = 3, prob=.7, size = 3)\nalosesprob=dbinom(x=1, size=3, prob=.7)\n(EV=(3*awinsprob1+2*awinsprob+alosesprob))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n(var=(1-EV*alosesprob)+(2-EV*awinsprob)+(3-EV*awinsprob1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.9567\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nBeta-Binomial distribution:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nawinsprob=dbbinom(x=2, alpha=7, beta = 3, size = 3)\nawinsprob1=dbbinom(x = 3, alpha=7, beta=3, size = 3)\nalosesprob=dbbinom(x=1, alpha = 7, beta=3, size =3)\n(EV=3*awinsprob1+2*awinsprob+alosesprob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n(var=(1-EV*alosesprob)+(2-EV*awinsprob)+(3-EV*awinsprob1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.995455\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nBoth distributions have an EV of 2.1. The variances differ slightly: Binomial distribution's is 3.9567, while the Beta-Binomial's is 3.9954. The Beta-Binomial distribution has a higher variance because of the added uncertainty around the chance of player A winning a match. The EV of 2.1 means that the mean number of legs won by player A is 2.1.\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\n**Solution**\n\nHere is the code and figure for when theta = .5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np=.7\ntheta=.5\nn=3\nx=-1:4\n\ndaltbinom = function(x, p, theta, n){\n  norm.c = 0\n  for (i in 0:n){\n    norm.c = norm.c + choose(n, i)* p^i * (1-p)^(n-i)* theta^(i*(n-i))\n  }\n  1/norm.c * choose(n, x) * p^x*(1-p)^(n-x)*theta^(x*(n-x))\n}\n\nggdat = tibble(x = -1:4) |>\n  rowwise() |>\n  mutate(PMF = daltbinom(x, p, theta, n))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = .5.](Lab8WriteUp_files/figure-pdf/fig-bar-daltbinom-theta.5-player-A-wins-1.pdf){#fig-bar-daltbinom-theta.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nHere is the code and figure for when theta = 1.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta=1\nggdat = tibble(x = -1:4) |>\n  rowwise() |>\n  mutate(PMF = daltbinom(x, p, theta, n))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1.](Lab8WriteUp_files/figure-pdf/fig-bar-daltbinom-theta1-player-A-wins-1.pdf){#fig-bar-daltbinom-theta1-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\nHere is the code and figure for when theta is 1.5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta=1.5\n\nggdat = tibble(x = -1:4) |>\n  rowwise() |>\n  mutate(PMF = daltbinom(x, p, theta, n))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"x\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1.5](Lab8WriteUp_files/figure-pdf/fig-bar-daltbinom-theta1.5-player-A-wins-1.pdf){#fig-bar-daltbinom-theta1.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nStarting with theta = .5, we can see that the distribution is heavily skewed to player A winning three times. When theta = 1, we notice that the plot is exactly the same as the plot of the binomial distribution, where the probability of player A winning twice or three times is within .1, and the probability of player A winning once or no times (losing) is much smaller than the probability of winning. Comparing this to the third graph, where theta = 1.5, we can see that it becomes more likely for player A to win two games, and player A only winning one game is more likely than player A winning three. This is because theta acts as a sort of \"clumping factor\", where 1 is the binomial distribution, and when theta is lower than 1, the data is more spread out, while when theta is higher than 1, the data is more clumped towards the middle values, which are one and two wins. \n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\n**Solution**\n\nHere is the code and figure for when theta = .5\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = .5 \n\npaltbinom = function(x, p, theta, n){\n  ggdat = tibble(x = 0:x) |>\n  mutate(PMF = daltbinom(x, p, theta, n),\n  CDF = cumsum(PMF))\n}\ndata1 = paltbinom(4, p, theta, n) #should sum to 1\n# i chose to keep 4 because I think it makes the graph look better. It is impossible for player A to achieve four wins since it is best out of three. \n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==21),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = .5](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta.5-player-A-wins-1.pdf){#fig-bar-paltbinom-theta.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nHere is the code and figure for when theta = 1. \n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = 1\ndata1 = paltbinom(4, p, theta, n) # should add to 1\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==21),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta1-player-A-wins-1.pdf){#fig-bar-paltbinom-theta1-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nHere is the code and figure for when theta = 1.5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = 1.5\ndata1 = paltbinom(4, p, theta, n) #should add to 1\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==21),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1.5](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta1.5-player-A-wins-1.pdf){#fig-bar-paltbinom-theta1.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nThe probability statement for player A winning the match is P(x >= 2). In terms of the CDF (represented by f(x)), this can be written as 1 - f(2). Here is the code where the probability is computed, using the Multiplicative Binomial Distribution. When theta is .5, player A has a .86 chance of winning. This is greater than the chance from the binomial and beta-binomial distributions. When theta is one, player A has a .78 chance of winning. Notably, this is the same as the binomial model. When theta is 1.5, player A has a .74 chance of winning. This is less than the beta-binomial and binomial distributions. As theta increases, player A's win chance decreases. This can be explained by the \"hot-hand\" effect hurting player A, since a higher theta means the data is more clumped, and victories where player A doesn't lose are less common.\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np =.7\ntheta = .5   \n#scenario 1: player a wins 2-0   \nn =3      \nx =3      \np_2_0= daltbinom(x, p, theta, n) \n#scenario 2: player a wins 2-1\nn =3      \nx =2      \np_2_1 = daltbinom(x, p, theta, n) \n# adding the probabilities gives the total chance of winning\n(p_wins = p_2_0 + p_2_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417\n```\n\n\n:::\n\n```{.r .cell-code}\ndata1 = paltbinom(4, p, theta, n)\n```\n:::\n\n\n \\normalsize\n\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==2),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = .5](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta.5-player-A-wins-2-1.pdf){#fig-bar-paltbinom-theta.5-player-A-wins-2 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#theta = 1\np =.7\ntheta = 1   \n#scenario 1: player a wins 2-0   \nn =3      \nx =3      \np_2_0= daltbinom(x, p, theta, n) \n#scenario 2: player a wins 2-1\nn =3      \nx =2      \np_2_1 = daltbinom(x, p, theta, n) \n\n# adding the probabilities gives the total chance of winning, \n# which is the same as in the binomial distribution\n(p_wins = p_2_0 + p_2_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\n#the data that will be graphed\ndata1 = paltbinom(4, p, theta, n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==2),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta-1-player-A-wins-1.pdf){#fig-bar-paltbinom-theta-1-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#theta = 1.5\n\np =.7\ntheta = 1.5   \n#scenario 1: player a wins 2-0   \nn =3      \nx =3      \np_2_0= daltbinom(x, p, theta, n) \n#scenario 2: player a wins 2-1\nn =3      \nx =2      \np_2_1 = daltbinom(x, p, theta, n) \n\n# adding the probabilities gives the total chance of winning\n(p_wins = p_2_0 + p_2_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.746993\n```\n\n\n:::\n\n```{.r .cell-code}\ndata1 = paltbinom(4, p, theta, n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = data1) +\n geom_step(aes(x = x, y = CDF)) +\n geom_point(aes(x = x, y = CDF), size = 1) +\n geom_point(data = data1 |> filter(x==2),\n aes(x = x, y = CDF), size = 1, color=\"darkorchid2\") +\n geom_hline(yintercept = 0) +\n xlab(\"Wins by player A\") +\n ylab(\"Cumulative Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1.5 ](Lab8WriteUp_files/figure-pdf/fig-bar-paltbinom-theta-1.5-player-A-wins-1.pdf){#fig-bar-paltbinom-theta-1.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n\n\n\n<!-- $$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\}) $$ -->\n\n**I had to comment out the PMF integral because otherwise my r chunks below it would not work.** \n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\n\n\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals. \n\n**Solution**\nHere is the code defining my function. I reused my daltbinom function to make it easier to type out.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom= function(x, theta, n, alpha, beta)\n    {\n  integrate(f = function(p) {daltbinom(x, p, theta, n)*(gamma(alpha+beta)/(gamma(alpha)*gamma(beta))*p^(alpha-1)*(1-p)^(beta-1))}, \n  lower = 0, \n  upper = 1\n  )$value\n}\n```\n:::\n\n\n \\normalsize\n\nHere is the function applied for the first case, where alpha = 7, beta = 3, and theta = .5.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\ntheta = .5\nn=3\n\nggdat <- tibble(\n  x   = 0:n,\n  PMF = sapply(0:n, function(x) daltbbinom(x = x, theta = theta, n = n, alpha = alpha, beta = beta))\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"Number of wins by player A\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = .5](Lab8WriteUp_files/figure-pdf/fig-bar-daltbbinom-theta.5-player-A-wins-1.pdf){#fig-bar-daltbbinom-theta.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThis graph shows the probability of  of player A winning two or three games, and thus the match. This distribution appears to be heavily skewed to player A winning 3 games the majority of the time.\n\nHere is my code and graph for when theta = 1.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\ntheta = 1\nn=3\nggdat <- tibble(\n  x   = 0:n,\n  PMF = sapply(0:n, function(x) daltbbinom(x = x, theta = theta, n = n, alpha = alpha, beta = beta))\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"Number of wins by player A\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1](Lab8WriteUp_files/figure-pdf/fig-bar-daltbbinom-theta1-player-A-wins-1.pdf){#fig-bar-daltbbinom-theta1-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThis figure, where theta = 1, shows that the probability of player A winning three games significantly decreased, while the probability of player A winning one or two games increased. This again shows how theta works as a clumping factor, since now the data is more centered. \n\n\nThis is the case where theta = 1.5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\ntheta = 1.5\nn=3\nggdat <- tibble(\n  x   = 0:n,\n  PMF = sapply(0:n, function(x) daltbbinom(x = x, theta = theta, n = n, alpha = alpha, beta = beta))\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot() +\n geom_linerange(data = ggdat,\n aes(x = x, ymin = 0, ymax = PMF)) +\n geom_linerange(data = ggdat |> filter (x>1),\n aes(x = x, ymin = 0, ymax = PMF), color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n geom_hline(yintercept = 0) +\n scale_x_continuous(\"Number of wins by player A\", breaks=0:10) +\n ylab(\"Probability\") +\n theme_bw()\nPMF.plot\n```\n\n::: {.cell-output-display}\n![The probability of player A winning when theta = 1.5](Lab8WriteUp_files/figure-pdf/fig-bar-daltbbinom-theta1.5-player-A-wins-1.pdf){#fig-bar-daltbbinom-theta1.5-player-A-wins fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nIn this figure, the clumping towards the middle of the dataset continues, as the probability of three wins decreases again while the probability of one or two wins increases correspondingly. As such, player A is more likely to win the two out of three contest when theta = .5 (probability of .808), less likely to win when theta = 1 (probability of .764), and least likely to win when theta = 1.5 (probability of .739).\n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np=.7 #prob of winning\nq=1-p #prob of losing\np_0_2 = q*q\np_1_2 = (p*q*q)+(q*p*q) #doesn't matter which of the first two\n# games player A wins, so add probabilities of both senarios occuring\np_2_1 = (p*q*p)+(q*p*p) #same logic as above \np_2_0 = p*p\n\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_0_2, p_1_2, p_2_1, p_2_0)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nCDF.plot = ggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\nCDF.plot\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the binomial distribution](Lab8WriteUp_files/figure-pdf/fig-bar-binom-situations-1.pdf){#fig-bar-binom-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n* **Negative Binomial**\\\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq =1 - p\np_0_2 = dnbinom(x = 0, size = 2, prob = q)\np_1_2 = dnbinom(x = 1, size = 2, prob = q)\np_2_1 = dnbinom(x = 1, size = 2, prob = p)\np_2_0 = dnbinom(x = 0, size = 2, prob = p)\n\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_0_2, p_1_2, p_2_1, p_2_0)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the negative binomial distribution](Lab8WriteUp_files/figure-pdf/fig-bar-neg-binom-situations-1.pdf){#fig-bar-neg-binom-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n* **Beta-Binomial**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_0_2 = dbbinom(x = 0, size = 3, alpha = 7, beta = 3)\np_1_2 = dbbinom(x = 1, size = 3, alpha = 7, beta = 3)\np_2_1 = dbbinom(x = 2, size = 3, alpha = 7, beta = 3)\np_2_0 = dbbinom(x = 2, size = 3, alpha = 7, beta = 3)\n\n# Sanity check\np_0_2 + p_1_2 + p_2_1 + p_2_0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_0_2, p_1_2, p_2_1, p_2_0)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the beta binomial distribution](Lab8WriteUp_files/figure-pdf/fig-beta-binom-situations-1.pdf){#fig-beta-binom-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Solution**\n\nIn this code, theta = .5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np=.7\ntheta=.5\nn=3\nx=-1:4\np_x0 <- daltbinom(x=0, p, theta, n)\n p_x1 <- daltbinom(x=1, p, theta, n)  \n p_x2 <- daltbinom(x=2, p, theta, n)  \n p_x3 <- daltbinom(x=3, p, theta, n)\n\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_x0, p_x1, p_x2, p_x3)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the Althman Binomial distribution where theta = .5](Lab8WriteUp_files/figure-pdf/fig-althman-binom-theta.5-situations-1.pdf){#fig-althman-binom-theta.5-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nIn this code, theta = 1.5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np=.7\ntheta=1.5\nn=3\nx=-1:4\np_x0 <- daltbinom(x=0, p, theta, n)\n p_x1 <- daltbinom(x=1, p, theta, n)  \n p_x2 <- daltbinom(x=2, p, theta, n)  \n p_x3 <- daltbinom(x=3, p, theta, n)\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_x0, p_x1, p_x2, p_x3)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the Althman Binomial distribution where theta = 1.5](Lab8WriteUp_files/figure-pdf/fig-althman-binom-theta-1.5-situations-1.pdf){#fig-althman-binom-theta-1.5-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Solution**\nThis is the code and figure for when theta = .5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta=.5\nn=3\nx=-1:4\nalpha=7\nbeta=3\np_x0 <- daltbbinom(x=0, theta=theta, n=n, alpha = alpha, beta=beta)\np_x1 <- daltbbinom(x=1,  theta=theta, n=n, alpha = alpha, beta=beta)  \np_x2 <- daltbbinom(x=2,  theta=theta, n=n, alpha = alpha, beta=beta)  \np_x3 <- daltbbinom(x=3, theta=theta, n=n, alpha = alpha, beta=beta)\n\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_x0, p_x1, p_x2, p_x3) #sanity check - they sum to 1\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the Althman Beta Binomial distribution where theta = .5](Lab8WriteUp_files/figure-pdf/fig-althman-beta-binom-theta-.5-situations-1.pdf){#fig-althman-beta-binom-theta-.5-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThis is the code and figure for when theta = 1.5.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np=.7\ntheta=1.5\nn=3\nx=-1:4\nalpha=7\nbeta=3\np_x0 <- daltbbinom(x=0, theta=theta, n=n, alpha = alpha, beta=beta)\np_x1 <- daltbbinom(x=1,  theta=theta, n=n, alpha = alpha, beta=beta)  \np_x2 <- daltbbinom(x=2,  theta=theta, n=n, alpha = alpha, beta=beta)  \np_x3 <- daltbbinom(x=3, theta=theta, n=n, alpha = alpha, beta=beta)\n\nresults = tibble(\n  outcome = c(\"A loses 0-2\", \"A loses 1-2\", \"A wins 2-1\", \"A wins 2-0\"),\n  probability  = c(p_x0, p_x1, p_x2, p_x3)\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(data = results) +\n geom_col(aes(x = outcome, y = probability)) +\n geom_hline(yintercept = 0) +\n xlab(\"Situation\") +\n ylab(\"Probability\") +\n theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of different scenarios in the Althman Beta Binomial distribution where theta = 1.5](Lab8WriteUp_files/figure-pdf/fig-althman-beta-binom-theta-1.5-situations-1.pdf){#fig-althman-beta-binom-theta-1.5-situations fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\nThe binomial distribution and the negative binomial distribution have the same probabilites for all situations in the context of a best two-out-of-three match. The beta binomial distribution, however, incorporates variance into the skill and thus the win probability of player A. This effect can be seen by it being less likely for player A to win 2-0, but more likely for player A to win 2-1. \nThe Althman binomial distribution adds a \"hot-hand\" effect, where winning a leg boosts the probability that player A wins the next one. It also incorporates theta, which functions as a clumping value. For theta = .5, correspondingly, the probability that player A wins 2-0 is approximately triple the next likelist outcome. As theta increases to 1.5, the data becomes more \"clumped\" away from the extreme outcomes, and the probability of A winning or losing 2-0 decreases, while the probabilities of A winning 2-1 or losing 1-2 increase substantially. \nThe Althman beta binomial distribution combines the effects of Althman's and the beta distribution. Variance in player A's skill and a clumping factor are both added, and the result can be seen by A winning 2-0 being more likely in this distribution than in the normal Althman's distribution. ",
    "supporting": [
      "Lab8WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}